[package]
name = "xui-f"
version = "0.1.0"
edition = "2024"

[dependencies]
fontique = "0.10.0"
harfrust = "0.5.2"
self_cell = "1.2.2"
skrifa = "0.42.1"
unicode-bidi = "0.3.18"
unicode-linebreak = "0.1.5"
unicode-script = "0.5.8"
unicode-segmentation = "1.13.2"
xui-interface = { path = "../xui-interface" }
