//! The runtime contract behind the `xui!` macro.
//!
//! `xui!` is a *purely syntactic* transform: `<tag attr={expr}>children</tag>`
//! becomes `tag().attr(expr).into_element(children)`. It knows no tag names and
//! no attribute names. Everything a tag accepts is decided here, by the type
//! system:
//!
//! - **Constructor** — `<tag>` requires a function `tag()` in scope returning a
//!   builder. Host widgets export theirs from [`crate::widgets`]; components get
//!   one generated by `#[component]`. A misspelled tag is a plain
//!   `cannot find function` error.
//! - **Attributes** — `attr={expr}` is `.attr(expr)`. Style properties come from
//!   the blanket [`StyleProps`] trait, widget-specific ones from inherent
//!   methods (which take precedence over the trait, so a widget can override a
//!   generic property). A misspelled attribute is rustc's own
//!   `no method named ... did you mean ...?`, pointed at the attribute.
//! - **Children** — the macro passes one of [`NoChildren`], [`Children`], or
//!   [`Content`] to [`IntoElement`], and the widget decides which of those it
//!   accepts. `<canvas>{x}</canvas>` fails to compile because `CanvasWidget`
//!   only implements `IntoElement<NoChildren>`.
//!
//! Adding a style property, a widget, or a component therefore never requires a
//! change to `xui-macros`.

use std::sync::Arc;

use crate::core::{EdgeInsets, Point, Size};
use crate::element::{ElementDesc, IntoChildren};
use crate::style::{
    AlignStyle, BackdropStyle, ColorStyle, ColorValue, CursorIcon, Effect, JustifyStyle, LengthValue,
    PositionStyle, ScrollDirectionStyle, ScrollbarStyle, ScrollbarStylePatch,
    ScrollbarVisibilityStyle, ShadowStyle, StrokeLineStyle, StrokeStyle, Style, StyleMerge,
    TransformStyle,
};
use xui_animation::Transition;
use xui_interface::{
    FontFamily, FontStyle, FontWeight, LineHeight, Sizing, TextContent, TextDecoration,
};

// ---------------------------------------------------------------------------
// Children
// ---------------------------------------------------------------------------

/// `<tag />` — the tag was written without a body.
pub struct NoChildren;

/// `<tag><a /><b /></tag>` — an element list collected by the macro.
pub struct Children(pub Vec<ElementDesc>);

/// `<tag>{expr}</tag>` — a single braced expression, meaning whatever the
/// receiving widget says it means. Containers read it as children (via
/// [`IntoChildren`]); `text` reads it as its text content.
pub struct Content<T>(pub T);

/// Turns a widget or component builder into an [`ElementDesc`], given whatever
/// the macro found between the tags.
///
/// Implement it once per accepted child shape. Not implementing a shape is how
/// a widget rejects it at compile time.
#[diagnostic::on_unimplemented(
    message = "`<{Self}>` does not accept this kind of body",
    label = "not a valid body for this element",
    note = "`NoChildren` = `<tag />`, `Children` = `<tag><a /><b /></tag>`, \
            `Content<T>` = `<tag>{{expr}}</tag>`",
    note = "a leaf element such as `canvas` or `icon` accepts no body at all"
)]
pub trait IntoElement<C> {
    fn into_element(self, children: C) -> ElementDesc;
}

/// The three body shapes `xui!` can produce, and the entry point it actually
/// emits.
///
/// Dispatching *from the body* rather than from the widget is what makes the
/// diagnostic above fire. With `build(widget, body)` as a free function, a
/// widget that has exactly one `IntoElement` impl lets inference unify the body
/// type with that impl and the error degrades to `expected NoChildren, found
/// Content<_>`. Here `Self` is pinned by the receiver, so `W: IntoElement<Self>`
/// is a genuine unsatisfied bound.
pub trait ElementBody: Sized {
    fn build<W: IntoElement<Self>>(self, widget: W) -> ElementDesc {
        widget.into_element(self)
    }
}

impl ElementBody for NoChildren {}
impl ElementBody for Children {}
impl<T> ElementBody for Content<T> {}

impl Children {
    pub fn collect(self) -> Vec<ElementDesc> {
        self.0
    }
}

impl<T: IntoChildren> Content<T> {
    pub fn collect(self) -> Vec<ElementDesc> {
        let mut children = Vec::new();
        self.0.append_children(&mut children);
        children
    }
}

// ---------------------------------------------------------------------------
// Style properties
// ---------------------------------------------------------------------------

/// A builder that owns a [`Style`], which [`StyleProps`] then decorates with the
/// whole style vocabulary.
pub trait Styled: Sized {
    fn map_style(self, f: impl FnOnce(Style) -> Style) -> Self;
}

macro_rules! style_props {
    (
        $(
            $name:ident ( $( $arg:ident : $ty:ty ),* $(,)? ) => $target:ident ;
        )*
        @manual { $($manual:tt)* }
    ) => {
        /// Every [`Style`] property, as a builder method on every styled widget.
        ///
        /// Blanket-implemented for all [`Styled`] types, so a widget gets the
        /// full vocabulary from a three-line `Styled` impl. Inherent methods win
        /// over these, which is how `IconWidget::color` can mean "tint" while
        /// `StyleProps::color` means "text color" everywhere else.
        pub trait StyleProps: Styled {
            $(
                fn $name(self, $( $arg: $ty ),*) -> Self {
                    self.map_style(move |__style| __style.$target( $( $arg ),* ))
                }
            )*
            $($manual)*
        }

        impl<T: Styled> StyleProps for T {}
    };
}

style_props! {
    // text
    color(color: impl Into<ColorValue>) => color;
    font_family(family: impl Into<FontFamily>) => font_family;
    font_size(size: impl Into<LengthValue>) => font_size;
    font_weight(weight: FontWeight) => font_weight;
    font_style(style: FontStyle) => font_style;
    line_height(height: LineHeight) => line_height;
    letter_spacing(spacing: impl Into<LengthValue>) => letter_spacing;
    decoration(decoration: TextDecoration) => decoration;

    // layout
    gap(gap: impl Into<LengthValue>) => gap;
    size(size: impl Into<Size<Sizing>>) => size;
    width(width: impl Into<Sizing>) => width;
    height(height: impl Into<Sizing>) => height;
    min_size(size: impl Into<Size<Sizing>>) => min_size;
    min_width(width: impl Into<Sizing>) => min_width;
    min_height(height: impl Into<Sizing>) => min_height;
    max_size(size: Size<Sizing>) => max_size;
    max_width(width: impl Into<Sizing>) => max_width;
    max_height(height: impl Into<Sizing>) => max_height;
    margin(margin: EdgeInsets) => margin;
    padding(padding: EdgeInsets) => padding;
    align(align: AlignStyle) => align;
    justify(justify: JustifyStyle) => justify;
    inset(inset: EdgeInsets) => inset;
    // `position_type` reads badly as an attribute; the rename lives here rather
    // than in the macro so that the macro keeps zero exceptions.
    position(position: PositionStyle) => position_type;

    // transform
    transform(transform: TransformStyle) => transform;
    translate(translate: Point) => translate;
    translate_x(x: f32) => translate_x;
    translate_y(y: f32) => translate_y;
    scale(scale: f32) => scale;
    scale_xy(scale: Point) => scale_xy;
    rotate(radians: f32) => rotate;
    transform_origin(origin: Point) => transform_origin;

    // paint
    background(color: impl Into<ColorStyle>) => background;
    border_color(color: impl Into<ColorStyle>) => border_color;
    border_width(width: impl Into<LengthValue>) => border_width;
    border_radius(radius: impl Into<LengthValue>) => border_radius;
    stroke(stroke: StrokeStyle) => stroke;
    shadow(shadow: ShadowStyle) => shadow;
    clip(clip: bool) => clip;
    cursor(cursor: CursorIcon) => cursor;
    backdrop_blur(sigma: impl Into<LengthValue>) => backdrop_blur;
    backdrop_style(backdrop: BackdropStyle) => backdrop_style;
    effects(effects: impl Into<Arc<[Effect]>>) => effects;

    // scroll
    scroll_direction(direction: ScrollDirectionStyle) => scroll_direction;
    scrollbar_style(scrollbar: ScrollbarStyle) => scrollbar_style;
    scrollbar(scrollbar: ScrollbarStylePatch) => scrollbar;
    scrollbar_width(width: impl Into<LengthValue>) => scrollbar_width;
    scrollbar_track_color(color: impl Into<ColorStyle>) => scrollbar_track_color;
    scrollbar_thumb_color(color: impl Into<ColorStyle>) => scrollbar_thumb_color;
    scrollbar_radius(radius: impl Into<LengthValue>) => scrollbar_radius;
    scrollbar_visibility(visibility: ScrollbarVisibilityStyle) => scrollbar_visibility;

    // animation
    transition(transition: Transition) => transition;

    @manual {
        /// Multi-argument style setters take a tuple, so that every attribute
        /// stays a single `name={value}` pair.
        fn stroke_style(
            self,
            stroke: (
                impl Into<ColorStyle>,
                impl Into<LengthValue>,
                StrokeLineStyle,
            ),
        ) -> Self {
            let (color, width, line_style) = stroke;
            self.map_style(move |style| style.stroke_style(color, width, line_style))
        }

        fn box_shadow(
            self,
            shadow: (
                impl Into<ColorValue>,
                Point,
                impl Into<LengthValue>,
                impl Into<LengthValue>,
            ),
        ) -> Self {
            let (color, offset, blur, spread) = shadow;
            self.map_style(move |style| style.box_shadow(color, offset, blur, spread))
        }

        fn no_stroke(self, no_stroke: bool) -> Self {
            self.map_style(move |style| if no_stroke { style.no_stroke() } else { style })
        }

        fn no_shadow(self, no_shadow: bool) -> Self {
            self.map_style(move |style| if no_shadow { style.no_shadow() } else { style })
        }

        fn no_backdrop(self, no_backdrop: bool) -> Self {
            self.map_style(move |style| if no_backdrop { style.no_backdrop() } else { style })
        }
    }
}

// ---------------------------------------------------------------------------
// Host widget wiring
// ---------------------------------------------------------------------------

macro_rules! impl_styled {
    ($($widget:ty),* $(,)?) => {
        $(
            impl Styled for $widget {
                fn map_style(mut self, f: impl FnOnce(Style) -> Style) -> Self {
                    self.style = f(::std::mem::take(&mut self.style));
                    self
                }
            }
        )*
    };
}

/// Declares which child shapes a host widget accepts.
macro_rules! impl_host_element {
    (parent $widget:ty) => {
        impl IntoElement<NoChildren> for $widget {
            fn into_element(self, _: NoChildren) -> ElementDesc {
                self.into_element_desc(Vec::new())
            }
        }

        impl IntoElement<Children> for $widget {
            fn into_element(self, children: Children) -> ElementDesc {
                self.into_element_desc(children.collect())
            }
        }

        impl<T: IntoChildren> IntoElement<Content<T>> for $widget {
            fn into_element(self, content: Content<T>) -> ElementDesc {
                self.into_element_desc(content.collect())
            }
        }
    };
    (leaf $widget:ty) => {
        impl IntoElement<NoChildren> for $widget {
            fn into_element(self, _: NoChildren) -> ElementDesc {
                self.into_element_desc()
            }
        }
    };
}

use crate::widgets::{
    CanvasWidget, ContainerWidget, GridWidget, IconWidget, ImageWidget, TextWidget, ZStackWidget,
};

impl_styled!(
    ContainerWidget,
    GridWidget,
    ZStackWidget,
    ImageWidget,
    CanvasWidget,
    IconWidget,
    TextWidget,
);

impl_host_element!(parent ContainerWidget);
impl_host_element!(parent GridWidget);
impl_host_element!(parent ZStackWidget);
impl_host_element!(parent ImageWidget);
impl_host_element!(leaf CanvasWidget);
impl_host_element!(leaf IconWidget);

impl IntoElement<NoChildren> for TextWidget {
    fn into_element(self, _: NoChildren) -> ElementDesc {
        self.into_element_desc()
    }
}

/// `<text>{expr}</text>` sets the text content rather than adding children.
impl<T: Into<TextContent>> IntoElement<Content<T>> for TextWidget {
    fn into_element(self, content: Content<T>) -> ElementDesc {
        self.text(content.0).into_element_desc()
    }
}
