pub mod animation;
pub mod app;
pub mod assets;
pub mod component;
pub mod core;
pub mod element;
pub mod render;
pub mod transition;
// pub mod event;
pub mod event_system;
pub mod fiber;
pub mod focus;
#[cfg(test)]
mod frame_bench;
pub mod lanes;
pub mod layout;
pub mod prelude;
pub mod runtime;
pub mod shortcut;
pub mod state;
pub mod style;
pub mod widgets;
pub use crate::prelude::*;
pub use xui_macros::main;
pub use xui_text::engine::Engine;
pub mod text;
pub mod ui_runtime;

/// Includes the bootstrap module generated by `cargo xui`.
///
/// Invoke this once at the application crate root. It defines `xui_assets`, containing
/// generated resource constants and a `manager()` constructor.
#[macro_export]
macro_rules! include_assets {
    () => {
        include!(env!(
            "XUI_ASSETS_BOOTSTRAP",
            "XUI assets require building through `cargo xui`"
        ));
    };
}
