[package]
name = "xui-pak"
version = "0.1.0"
edition = "2024"

[dependencies]
blake3 = { workspace = true }
camino = { workspace = true }
memmap2 = { workspace = true }
postcard = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
zstd = { workspace = true }

[dev-dependencies]
tempfile = "3"
