[package]
name = "xui-example-app"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "xui-example-app"
path = "src/main.rs"

[dependencies]
winit = "0.30.12"
xui = { path = "../xui" }
xui-winit = { path = "../xui-winit" }
xui-components = { path = "../xui-components" }
leanplot = { git = "https://github.com/sleptworld/LeanPlot.git" }

[features]
default = ["skia"]
skia = ["xui-winit/skia"]

[dev-dependencies]
png = "0.18.1"
xui-skia = { path = "../xui-skia" }
xui-text-engine = { path = "../xui-text-engine" }
