[package]
name = "xui-example-app"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "xui-example-app"
path = "src/main.rs"

[dependencies]
xui-core = { path = "../crates/xui-core" }
xui-macos = { path = "../crates/xui-macos", features=["skia"] }
xui-components = { path = "../xui-components" }
leanplot = { git = "https://github.com/sleptworld/LeanPlot.git" }


[dev-dependencies]
png = "0.18.1"
xui-skia = { path = "../crates/xui-skia" }
xui-cosmic = { path = "../crates/xui-cosmic" }

[build-dependencies]
xui-build = { version = "0.1.0", path = "../crates/xui-build" }
