[package]
name = "xui-skia"
version = "0.1.0"
edition = "2024"

[dependencies]
memmap2.workspace = true
moka = { version = "0.12.15", features = ["sync"] }
skia-safe = { version = "0.99.0", features = ["gpu", "textlayout"] }
softbuffer = "0.4.8"
thiserror = "2.0.18"
winit = "0.30.12"
xui = { path = "../xui" }
xui-interface = { path = "../xui-interface" }
xui-render-graph = { path = "../xui-render-graph" }

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.4"
objc2-core-foundation = "0.3.2"
objc2-metal = { version = "0.3.2", features = ["MTLCommandBuffer", "MTLCommandQueue", "MTLDevice", "MTLDrawable", "MTLTexture"] }
objc2-quartz-core = { version = "0.3.2", features = ["CALayer", "CAMetalLayer"] }
raw-window-metal = "1.1.0"
skia-safe = { version = "0.99.0", features = ["gpu", "metal", "textlayout"] }

[target.'cfg(target_os = "linux")'.dependencies]
ash = "0.38"
ash-window = "0.13"
skia-safe = { version = "0.99.0", features = ["gpu", "vulkan", "textlayout"] }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62", features = [
    "Win32_Foundation",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D12",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Security",
    "Win32_System_Threading",
] }
skia-safe = { version = "0.99.0", features = ["gpu", "d3d", "textlayout"] }

[dev-dependencies]
xui-text-engine = { path = "../xui-text-engine" }
