[package]
name = "xui-winit"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.25.0", features = ["derive"] }
etagere = "0.3.0"
pollster = "0.4.0"
wgpu = "29.0.3"
winit = "0.30.12"
xui = { path = "../xui" }
xui-interface = { path = "../xui-interface" }
xui-text = { path = "../xui-text" }

glam = { workspace = true }
thiserror = "2.0.18"
log = "0.4.29"
cosmic-text = "0.19.0"
moka = { version = "0.12.15", features = ["sync"] }
