[package]
name = "xui"
version = "0.1.0"
edition = "2024"

[dependencies]
rustc-hash = "2.1.2"
slotmap = "1.1.1"
smallstr = "0.3.1"
smallvec = "1.15.1"
moka = { version = "0.12.15", features = ["sync"] }
taffy = "0.13.0"
xui-animation = { path = "../xui-animation" }
xui-assets = { path = "../xui-assets" }
xui-interface = { path = "../xui-interface" }
xui-macros = { path = "../xui-macros" }
slot = { path = "../slot" }
bitflags = "2.13.0"
ropey = "1.6.1"
zune-core = { workspace = true }
zune-image = { workspace = true }
tokio.workspace = true
num-traits = "0.2.19"
usvg = { version = "0.47.0", default-features = false }
quick_cache = { version = "0.7.0", default-features = false }
xui-render-graph = { path = "../xui-render-graph" }

[dev-dependencies]
trybuild = "1.0.120"
xui-cosmic = { path = "../xui-cosmic" }
