[package]
name = "xui"
version = "0.1.0"
edition = "2024"

[dependencies]
xui-animation = {path="../crates/xui-animation"}
xui-core = {path="../crates/xui-core"}
xui-interface = {path="../crates/xui-interface"}
xui-macros = {path="../crates/xui-macros"}

[target.'cfg(target_os = "macos")'.dependencies]
xui-macos = {path="../crates/xui-macos" ,features=["skia"]}
