[package]
name = "xui"
version = "0.1.0"
edition = "2024"

[dependencies]
rustc-hash = "2.1.2"
slotmap = "1.1.1"
smallstr = "0.3.1"
smallvec = "1.15.1"
taffy = "0.10.1"
xui-interface = { path = "../xui-interface" }
xui-macros = { path = "../xui-macros" }
xui-text = { path = "../xui-text" }
slot = { path = "../slot" }
